/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_unafraid_remote_control_api_RCDriver */

#ifndef _Included_com_github_unafraid_remote_control_api_RCDriver
#define _Included_com_github_unafraid_remote_control_api_RCDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_unafraid_remote_control_api_RCDriver
 * Method:    sendPacket
 * Signature: (IBBBB)I
 */
JNIEXPORT jint JNICALL Java_com_github_unafraid_remote_control_api_RCDriver_sendPacket
  (JNIEnv *, jobject, jint, jbyte, jbyte, jbyte, jbyte);

#ifdef __cplusplus
}
#endif
#endif
